In [1]:
import torch
from torch.utils.data import DataLoader

from fmri_reconstruction_with_dmvae.mnist_svhn.dataset import getPairedDataset
from fmri_reconstruction_with_dmvae.mnist_svhn.util import unpack_data

if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

In [2]:
data_path = '../../data/mnist_svhn'

num_workers = 4
cuda = torch.cuda.is_available()

batch_size = 100

train_mnist_svhn, test_mnist_svhn = getPairedDataset(data_path, 100, cuda=cuda)
kwargs = {'num_workers': num_workers, 'pin_memory': True} if cuda else {}
train_loader = DataLoader(train_mnist_svhn, batch_size=batch_size, shuffle=True, **kwargs)
test_loader = DataLoader(test_mnist_svhn, batch_size=batch_size, shuffle=False, **kwargs)

In [3]:
print(f"Size of train data: {len(train_mnist_svhn)}")
print(f"Size of test data: {len(test_mnist_svhn)}")

Size of train data: 1682040
Size of test data: 300000


In [8]:
# train_mnist_svhn[index][mnist(0) or svhn(1)][pixel values(0) or label(1)].shape
print(train_mnist_svhn[0][0][0].shape)  # shape of mnist pixel values
print(train_mnist_svhn[0][1][0].shape)  # shape of svhn pixel values
print(train_mnist_svhn[0][0][1])  # mnist label
print(train_mnist_svhn[0][1][1])  # svhn label

torch.Size([1, 28, 28])
torch.Size([3, 32, 32])
0
0


In [9]:
train_mnist_svhn[0][1]

(tensor([[[0.3608, 0.3843, 0.4275,  ..., 0.6471, 0.6745, 0.6824],
          [0.3333, 0.3608, 0.4196,  ..., 0.5725, 0.5961, 0.6000],
          [0.2941, 0.3373, 0.4196,  ..., 0.4784, 0.4902, 0.4941],
          ...,
          [0.2745, 0.3098, 0.3608,  ..., 0.6706, 0.6745, 0.6745],
          [0.4196, 0.4157, 0.4078,  ..., 0.5529, 0.5569, 0.5569],
          [0.5216, 0.4902, 0.4471,  ..., 0.4824, 0.4863, 0.4863]],
 
         [[0.3333, 0.3529, 0.3922,  ..., 0.6235, 0.6510, 0.6588],
          [0.3098, 0.3373, 0.3922,  ..., 0.5608, 0.5804, 0.5882],
          [0.2784, 0.3216, 0.4000,  ..., 0.4824, 0.4941, 0.4980],
          ...,
          [0.2941, 0.3373, 0.4000,  ..., 0.6510, 0.6549, 0.6549],
          [0.4353, 0.4353, 0.4392,  ..., 0.5333, 0.5333, 0.5294],
          [0.5294, 0.5059, 0.4745,  ..., 0.4588, 0.4549, 0.4510]],
 
         [[0.4000, 0.4235, 0.4667,  ..., 0.6000, 0.6275, 0.6353],
          [0.3882, 0.4157, 0.4706,  ..., 0.5412, 0.5608, 0.5647],
          [0.3686, 0.4118, 0.4902,  ...,

In [6]:
print(train_mnist_svhn[0][0][0])  # mnist pixel values

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [7]:
print(train_mnist_svhn[0][1][0])  # svhn pixel values

tensor([[[0.3608, 0.3843, 0.4275,  ..., 0.6471, 0.6745, 0.6824],
         [0.3333, 0.3608, 0.4196,  ..., 0.5725, 0.5961, 0.6000],
         [0.2941, 0.3373, 0.4196,  ..., 0.4784, 0.4902, 0.4941],
         ...,
         [0.2745, 0.3098, 0.3608,  ..., 0.6706, 0.6745, 0.6745],
         [0.4196, 0.4157, 0.4078,  ..., 0.5529, 0.5569, 0.5569],
         [0.5216, 0.4902, 0.4471,  ..., 0.4824, 0.4863, 0.4863]],

        [[0.3333, 0.3529, 0.3922,  ..., 0.6235, 0.6510, 0.6588],
         [0.3098, 0.3373, 0.3922,  ..., 0.5608, 0.5804, 0.5882],
         [0.2784, 0.3216, 0.4000,  ..., 0.4824, 0.4941, 0.4980],
         ...,
         [0.2941, 0.3373, 0.4000,  ..., 0.6510, 0.6549, 0.6549],
         [0.4353, 0.4353, 0.4392,  ..., 0.5333, 0.5333, 0.5294],
         [0.5294, 0.5059, 0.4745,  ..., 0.4588, 0.4549, 0.4510]],

        [[0.4000, 0.4235, 0.4667,  ..., 0.6000, 0.6275, 0.6353],
         [0.3882, 0.4157, 0.4706,  ..., 0.5412, 0.5608, 0.5647],
         [0.3686, 0.4118, 0.4902,  ..., 0.4627, 0.4745, 0.

In [11]:
for data in train_loader:
    unpacked_data = unpack_data(data, device)

    x1 = unpacked_data[0]
    x2 = unpacked_data[1]

    x1_label = data[0][1].cpu().numpy()
    x2_label = data[1][1].cpu().numpy()

    break

print(x1.shape)
print(x2.shape)
print(x1_label)
print(x2_label)

torch.Size([100, 1, 28, 28])
torch.Size([100, 3, 32, 32])
[2 8 6 9 4 3 3 1 1 3 7 6 1 0 1 4 2 2 0 2 3 0 7 6 3 4 4 8 0 0 1 4 2 0 5 9 1
 0 8 3 2 3 4 5 2 6 0 7 4 0 4 1 8 1 8 7 2 7 8 7 6 9 4 5 9 0 3 6 2 1 6 2 4 1
 2 3 0 2 5 7 0 6 7 7 4 7 8 6 6 6 7 7 8 1 3 2 0 1 4 1]
[2 8 6 9 4 3 3 1 1 3 7 6 1 0 1 4 2 2 0 2 3 0 7 6 3 4 4 8 0 0 1 4 2 0 5 9 1
 0 8 3 2 3 4 5 2 6 0 7 4 0 4 1 8 1 8 7 2 7 8 7 6 9 4 5 9 0 3 6 2 1 6 2 4 1
 2 3 0 2 5 7 0 6 7 7 4 7 8 6 6 6 7 7 8 1 3 2 0 1 4 1]
